version: "3.3"

services:
  db:
    image: postgres:13-alpine3.14
    env_file:
      - .env_docker

  web:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env_docker
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db





